-- ============================================
-- ENGLISH - 100 SATA QUESTIONS (SET 4)
-- Test ID: 00000000-0000-0000-0000-000000000001  ← shared bucket
-- Subject ID: 10000000-0000-0000-0000-000000000025
-- display_order: 301–400
-- is_multiple_choice: true (Select All That Apply)
-- Run AFTER FIX-ENGLISH-QUESTIONS-TEST-ID.sql
-- ============================================
-- Topic ID map:
--   Clinical English Terminology           → ...0399  (Q301–Q330)
--   Clinical Abbreviations in Context      → ...0400  (Q331–Q350)
--   Clinical Scenario Reading I            → ...0401  (Q351–Q370)
--   Clinical Scenario Reading II           → ...0402  (Q371–Q390)
--   Professional Nursing Communication     → ...0403  (Q391–Q400)
-- ============================================

INSERT INTO test_questions
  (test_id, topic_id, question_stem, options, correct_answers, is_multiple_choice, rationale, category, display_order)
VALUES

-- =============================================
-- Q301–Q330: Clinical English Terminology (SATA)
-- =============================================

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Regarding the clinical manifestations of a localized inflammatory response in a peripheral extremity, which of the following findings would a clinician identify as being not inconsistent with this diagnosis? Select all that apply.',
 '[{"id":"a","text":"A perceptible increase in local thermal energy."},{"id":"b","text":"A discernible shift toward a rubicund hue of the integument."},{"id":"c","text":"A reduction in the circumference of the affected area."},{"id":"d","text":"The presence of discomfort upon palpation."},{"id":"e","text":"A localized accumulation of interstitial fluid."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 '"Not inconsistent" means "consistent." Signs of inflammation include heat (A), redness/rubicund (B), pain (D), and swelling/edema (E). A reduction in size (C) is inconsistent with inflammation.',
 'Clinical English Terminology', 301),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following anatomical structures are situated in a position that is superior to the diaphragm? Select all that apply.',
 '[{"id":"a","text":"The hepatic lobes."},{"id":"b","text":"The cardiac muscle."},{"id":"c","text":"The pulmonary lobes."},{"id":"d","text":"The gastric cavity."},{"id":"e","text":"The renal organs."}]'::jsonb,
 ARRAY['b','c'], true,
 '"Superior" means above. Only the heart (B) and lungs (C) are above the diaphragm. The liver (A), stomach (D), and kidneys (E) are inferior.',
 'Clinical English Terminology', 302),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following descriptors would be considered medically synonymous with a patient who is "afebrile"? Select all that apply.',
 '[{"id":"a","text":"The patient''s temperature is exactly 37° Celsius."},{"id":"b","text":"The patient is exhibiting a core temperature of 102° Fahrenheit."},{"id":"c","text":"The patient is currently without an elevated thermal state."},{"id":"d","text":"The patient''s temperature resides within the range of normal homeostasis."},{"id":"e","text":"The patient is experiencing chills and rigors."}]'::jsonb,
 ARRAY['a','c','d'], true,
 '"Afebrile" means no fever. 37°C is normal (A), as is any state without elevation (C) or within homeostasis (D). 102°F (B) is a fever; chills/rigors (E) suggest fever.',
 'Clinical English Terminology', 303),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'In identifying "objective" data during a physical assessment, the clinician should focus upon which of the following findings? Select all that apply.',
 '[{"id":"a","text":"The patient''s verbal report of localized cephalalgia."},{"id":"b","text":"A measured radial pulse of 88 beats per minute."},{"id":"c","text":"The presence of a palpable mass in the abdomen."},{"id":"d","text":"A recorded blood pressure of 130/85 mmHg."},{"id":"e","text":"The patient''s statement that they feel very apprehensive."}]'::jsonb,
 ARRAY['b','c','d'], true,
 'Objective data is observable/measurable: pulse (B), a palpable mass (C), and BP (D). Pain description (A) and feelings (E) are subjective.',
 'Clinical English Terminology', 304),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following terms correctly describe the movement of a joint? Select all that apply.',
 '[{"id":"a","text":"Flexion: decreasing the angle between two bones."},{"id":"b","text":"Extension: increasing the angle between two bones."},{"id":"c","text":"Abduction: moving a limb toward the midline of the body."},{"id":"d","text":"Adduction: moving a limb away from the midline of the body."},{"id":"e","text":"Rotation: turning a bone around its own longitudinal axis."}]'::jsonb,
 ARRAY['a','b','e'], true,
 'Flexion (A), Extension (B), and Rotation (E) are correctly defined. Abduction (C) is moving *away* from midline, and Adduction (D) is moving *toward* midline — these definitions are reversed.',
 'Clinical English Terminology', 305),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following anatomical terms correctly describe the location of a structure? Select all that apply.',
 '[{"id":"a","text":"The heart is medial to the lungs."},{"id":"b","text":"The hand is distal to the elbow."},{"id":"c","text":"The nose is superior to the chin."},{"id":"d","text":"The spine is anterior to the sternum."},{"id":"e","text":"The skin is superficial to the muscles."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Heart is in the middle (A), hand is farther out from the trunk (B), nose is above (C), and skin is on top (E). The spine is *posterior* (behind) the sternum, not anterior (D).',
 'Clinical English Terminology', 306),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following anatomical terms are opposite of each other? Select all that apply.',
 '[{"id":"a","text":"Superior and Inferior."},{"id":"b","text":"Anterior and Posterior."},{"id":"c","text":"Medial and Lateral."},{"id":"d","text":"Proximal and Distal."},{"id":"e","text":"Superficial and Deep."}]'::jsonb,
 ARRAY['a','b','c','d','e'], true,
 'All pairs (A–E) are correctly matched as opposing anatomical directional terms.',
 'Clinical English Terminology', 307),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are considered primary functions of the skeletal system? Select all that apply.',
 '[{"id":"a","text":"The provision of a structural framework for the body."},{"id":"b","text":"The protection of vital internal organs."},{"id":"c","text":"The production of erythrocytes and other blood cells."},{"id":"d","text":"The storage of essential minerals like calcium."},{"id":"e","text":"The synthesis of Vitamin D via sunlight exposure."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'Framework (A), protection (B), blood cell production in marrow (C), and mineral storage (D) are skeletal functions. Vitamin D synthesis (E) is a function of the skin, not the skeleton.',
 'Clinical English Terminology', 308),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following items are considered part of the "appendicular" skeleton rather than the "axial" skeleton? Select all that apply.',
 '[{"id":"a","text":"The femur."},{"id":"b","text":"The vertebrae."},{"id":"c","text":"The humerus."},{"id":"d","text":"The cranium."},{"id":"e","text":"The phalanges."}]'::jsonb,
 ARRAY['a','c','e'], true,
 'The appendicular skeleton includes the limbs: femur (A), humerus (C), and finger bones (E). The axial skeleton is the central axis: vertebrae (B) and skull/cranium (D).',
 'Clinical English Terminology', 309),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are "water-soluble" vitamins? Select all that apply.',
 '[{"id":"a","text":"Vitamin A."},{"id":"b","text":"Vitamin B12."},{"id":"c","text":"Vitamin C."},{"id":"d","text":"Vitamin D."},{"id":"e","text":"Vitamin K."}]'::jsonb,
 ARRAY['b','c'], true,
 'B vitamins and Vitamin C are water-soluble. Vitamins A, D, E, and K are fat-soluble.',
 'Clinical English Terminology', 310),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are common "electrolytes" found in the human body? Select all that apply.',
 '[{"id":"a","text":"Sodium."},{"id":"b","text":"Potassium."},{"id":"c","text":"Calcium."},{"id":"d","text":"Glucose."},{"id":"e","text":"Magnesium."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Sodium (A), Potassium (B), Calcium (C), and Magnesium (E) are electrolytes. Glucose (D) is a carbohydrate/sugar, not an electrolyte.',
 'Clinical English Terminology', 311),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are primary components of blood? Select all that apply.',
 '[{"id":"a","text":"Erythrocytes."},{"id":"b","text":"Leukocytes."},{"id":"c","text":"Thrombocytes."},{"id":"d","text":"Plasma."},{"id":"e","text":"Alveoli."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'Red cells (A), white cells (B), platelets (C), and liquid plasma (D) are the four components of blood. Alveoli (E) are air sacs in the lungs.',
 'Clinical English Terminology', 312),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following organs are part of the digestive system? Select all that apply.',
 '[{"id":"a","text":"The esophagus."},{"id":"b","text":"The pancreas."},{"id":"c","text":"The kidneys."},{"id":"d","text":"The small intestine."},{"id":"e","text":"The spleen."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'The esophagus (A), pancreas (B), and small intestine (D) are digestive organs. The kidneys (C) are urinary; the spleen (E) is lymphatic/immune.',
 'Clinical English Terminology', 313),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are parts of the small intestine? Select all that apply.',
 '[{"id":"a","text":"The duodenum."},{"id":"b","text":"The jejunum."},{"id":"c","text":"The ileum."},{"id":"d","text":"The cecum."},{"id":"e","text":"The colon."}]'::jsonb,
 ARRAY['a','b','c'], true,
 'The small intestine has three parts: Duodenum, Jejunum, Ileum (D-J-I). The cecum (D) and colon (E) are parts of the large intestine.',
 'Clinical English Terminology', 314),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are parts of the large intestine? Select all that apply.',
 '[{"id":"a","text":"The duodenum."},{"id":"b","text":"The cecum."},{"id":"c","text":"The ascending colon."},{"id":"d","text":"The transverse colon."},{"id":"e","text":"The ileum."}]'::jsonb,
 ARRAY['b','c','d'], true,
 'The cecum (B) and colons (C, D) are large intestine structures. The duodenum (A) and ileum (E) belong to the small intestine.',
 'Clinical English Terminology', 315),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are functions of the liver? Select all that apply.',
 '[{"id":"a","text":"Production of bile."},{"id":"b","text":"Detoxification of harmful substances."},{"id":"c","text":"Storage of glycogen."},{"id":"d","text":"Production of insulin."},{"id":"e","text":"Synthesis of plasma proteins."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Bile production (A), detoxification (B), glycogen storage (C), and plasma protein synthesis (E) are liver functions. Insulin (D) is produced by the pancreas.',
 'Clinical English Terminology', 316),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are functions of the pancreas? Select all that apply.',
 '[{"id":"a","text":"Secretion of digestive enzymes like amylase and lipase."},{"id":"b","text":"Production of bile to emulsify fats."},{"id":"c","text":"Secretion of insulin into the bloodstream."},{"id":"d","text":"Regulation of blood glucose levels."},{"id":"e","text":"Production of hydrochloric acid."}]'::jsonb,
 ARRAY['a','c','d'], true,
 'Digestive enzymes (A), insulin secretion (C), and blood glucose regulation (D) are pancreatic functions. Bile (B) is made by the liver; hydrochloric acid (E) is made by the stomach.',
 'Clinical English Terminology', 317),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are primary organs of the endocrine system? Select all that apply.',
 '[{"id":"a","text":"The thyroid gland."},{"id":"b","text":"The pituitary gland."},{"id":"c","text":"The adrenal glands."},{"id":"d","text":"The spleen."},{"id":"e","text":"The pancreas."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Thyroid (A), pituitary (B), adrenal glands (C), and pancreas (E) are all endocrine organs that secrete hormones. The spleen (D) is part of the lymphatic/immune system.',
 'Clinical English Terminology', 318),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are functions of the integumentary system? Select all that apply.',
 '[{"id":"a","text":"Protection against pathogenic invasion."},{"id":"b","text":"Regulation of body temperature."},{"id":"c","text":"Production of Vitamin D."},{"id":"d","text":"Elimination of waste via perspiration."},{"id":"e","text":"Transport of oxygen to the brain."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'The skin protects (A), regulates temperature (B), synthesizes Vitamin D (C), and excretes waste in sweat (D). Oxygen transport (E) is a cardiovascular/respiratory function.',
 'Clinical English Terminology', 319),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are functions of the skin? Select all that apply.',
 '[{"id":"a","text":"Thermoregulation."},{"id":"b","text":"Protection from UV radiation."},{"id":"c","text":"Sensory perception."},{"id":"d","text":"Excretion of salts and water."},{"id":"e","text":"Digestion of carbohydrates."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'Temperature regulation (A), UV protection (B), sensory feeling (C), and sweat/excretion (D) are skin functions. Carbohydrate digestion (E) occurs in the GI tract.',
 'Clinical English Terminology', 320),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are functions of white blood cells? Select all that apply.',
 '[{"id":"a","text":"Fighting bacteria."},{"id":"b","text":"Producing antibodies."},{"id":"c","text":"Carrying oxygen."},{"id":"d","text":"Fighting viruses."},{"id":"e","text":"Clotting blood."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'White blood cells fight bacteria (A), produce antibodies (B), and fight viruses (D). Red blood cells carry oxygen (C); platelets/thrombocytes clot blood (E).',
 'Clinical English Terminology', 321),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are primary organs of the nervous system? Select all that apply.',
 '[{"id":"a","text":"The brain."},{"id":"b","text":"The spinal cord."},{"id":"c","text":"The nerves."},{"id":"d","text":"The heart."},{"id":"e","text":"The lungs."}]'::jsonb,
 ARRAY['a','b','c'], true,
 'The brain (A), spinal cord (B), and peripheral nerves (C) make up the nervous system. The heart (D) is cardiovascular; the lungs (E) are respiratory.',
 'Clinical English Terminology', 322),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are parts of the brainstem? Select all that apply.',
 '[{"id":"a","text":"The cerebrum."},{"id":"b","text":"The midbrain."},{"id":"c","text":"The pons."},{"id":"d","text":"The medulla oblongata."},{"id":"e","text":"The cerebellum."}]'::jsonb,
 ARRAY['b','c','d'], true,
 'The brainstem consists of the midbrain (B), pons (C), and medulla oblongata (D). The cerebrum (A) and cerebellum (E) are separate major divisions of the brain.',
 'Clinical English Terminology', 323),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are parts of the urinary system? Select all that apply.',
 '[{"id":"a","text":"The kidneys."},{"id":"b","text":"The ureters."},{"id":"c","text":"The gallbladder."},{"id":"d","text":"The bladder."},{"id":"e","text":"The urethra."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Kidneys (A), ureters (B), bladder (D), and urethra (E) form the urinary system. The gallbladder (C) stores bile and belongs to the digestive system.',
 'Clinical English Terminology', 324),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are anatomical structures found in the upper respiratory tract? Select all that apply.',
 '[{"id":"a","text":"The nasal cavity."},{"id":"b","text":"The pharynx."},{"id":"c","text":"The larynx."},{"id":"d","text":"The trachea."},{"id":"e","text":"The alveoli."}]'::jsonb,
 ARRAY['a','b','c'], true,
 'The nasal cavity (A), pharynx/throat (B), and larynx/voice box (C) are upper respiratory structures. The trachea (D) and alveoli (E) are lower respiratory.',
 'Clinical English Terminology', 325),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following anatomical structures are found in the lower respiratory tract? Select all that apply.',
 '[{"id":"a","text":"The larynx."},{"id":"b","text":"The trachea."},{"id":"c","text":"The bronchi."},{"id":"d","text":"The bronchioles."},{"id":"e","text":"The alveoli."}]'::jsonb,
 ARRAY['b','c','d','e'], true,
 'The trachea (B), bronchi (C), bronchioles (D), and alveoli (E) are lower respiratory structures. The larynx (A) is upper respiratory.',
 'Clinical English Terminology', 326),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following vitamins are fat-soluble? Select all that apply.',
 '[{"id":"a","text":"Vitamin A."},{"id":"b","text":"Vitamin B1."},{"id":"c","text":"Vitamin D."},{"id":"d","text":"Vitamin E."},{"id":"e","text":"Vitamin K."}]'::jsonb,
 ARRAY['a','c','d','e'], true,
 'Vitamins A, D, E, and K are fat-soluble (remembered as "ADEK"). Vitamin B1 (B) is water-soluble.',
 'Clinical English Terminology', 327),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are fat-soluble vitamins? Select all that apply.',
 '[{"id":"a","text":"Vitamin K."},{"id":"b","text":"Vitamin C."},{"id":"c","text":"Vitamin E."},{"id":"d","text":"Vitamin D."},{"id":"e","text":"Vitamin A."}]'::jsonb,
 ARRAY['a','c','d','e'], true,
 'Vitamins A, D, E, and K are fat-soluble. Vitamin C (B) is water-soluble.',
 'Clinical English Terminology', 328),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are parts of the skeleton? Select all that apply.',
 '[{"id":"a","text":"Cartilage."},{"id":"b","text":"Ligaments."},{"id":"c","text":"Bones."},{"id":"d","text":"Muscles."},{"id":"e","text":"Tendons."}]'::jsonb,
 ARRAY['a','b','c'], true,
 'Bones (C), cartilage (A), and ligaments (B) form the skeletal system. Muscles (D) and tendons (E) belong to the muscular system.',
 'Clinical English Terminology', 329),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000399',
 'Which of the following are "cardinal" vital signs? Select all that apply.',
 '[{"id":"a","text":"Temperature."},{"id":"b","text":"Blood pressure."},{"id":"c","text":"Pulse."},{"id":"d","text":"Weight."},{"id":"e","text":"Respirations."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'The four cardinal vital signs are Temperature (A), Blood Pressure (B), Pulse (C), and Respirations (E). Weight (D) is a clinical measurement but not a vital sign.',
 'Clinical English Terminology', 330),

-- =============================================
-- Q331–Q350: Clinical Abbreviations in Context (SATA)
-- =============================================

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'In the context of a patient strictly designated as "NPO" for a duration of no less than eight hours, which of the following actions, if performed by the patient, would constitute a direct violation of this specific medical mandate? Select all that apply.',
 '[{"id":"a","text":"The ingestion of a transparent, carbonated beverage."},{"id":"b","text":"The mastication and subsequent deglutition of solid nutrients."},{"id":"c","text":"The simple act of ambulating within the clinical environment."},{"id":"d","text":"The consumption of a small quantity of crushed ice."},{"id":"e","text":"Engaging in a telephonic conversation with a relative."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'NPO (nil per os) means nothing by mouth. Clear soda (A), solid food (B), and ice (D) are all oral intake violations. Walking (C) and talking on the phone (E) are not oral intake.',
 'Clinical Abbreviations in Context', 331),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following describe "NPO" status? Select all that apply.',
 '[{"id":"a","text":"No food by mouth."},{"id":"b","text":"No water by mouth."},{"id":"c","text":"No IV fluids allowed."},{"id":"d","text":"Usually required before surgery."},{"id":"e","text":"Usually required after a patient has a bowel movement."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'NPO means no food (A) or water (B) by mouth, and is most commonly ordered before surgical procedures (D). IV fluids (C) are usually continued or increased to compensate. (E) is not an indication for NPO.',
 'Clinical Abbreviations in Context', 332),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'When assessing the "Five Rights" of medication administration, which of the following scenarios represent a failure to adhere to the standard of practice regarding the "Right Patient"? Select all that apply.',
 '[{"id":"a","text":"Utilizing only the patient''s room number as a singular identifier."},{"id":"b","text":"Verifying the patient''s identity via a photographic ID and a birth date."},{"id":"c","text":"Administering the substance after checking the name on the wristband against the order."},{"id":"d","text":"Neglecting to ask the patient to state their full name prior to the task."},{"id":"e","text":"Relying solely on the patient''s verbal confirmation of their identity."}]'::jsonb,
 ARRAY['a','d','e'], true,
 'Standard practice requires two unique identifiers. Using only a room number (A), not asking the patient their name (D), and relying solely on verbal confirmation without a band check (E) are insufficient. (B) and (C) reflect proper two-identifier verification.',
 'Clinical Abbreviations in Context', 333),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Regarding the maintenance of "standard precautions" in a healthcare environment, which of the following actions should be performed universally, regardless of the patient''s perceived infection status? Select all that apply.',
 '[{"id":"a","text":"The utilization of gloves when contact with blood is anticipated."},{"id":"b","text":"The performance of hand hygiene following the removal of PPE."},{"id":"c","text":"The placement of all patients in a negative-pressure isolation room."},{"id":"d","text":"The disposal of used percutaneous implements in a puncture-resistant container."},{"id":"e","text":"The wearing of a sterile gown for every patient interaction."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'Standard precautions include gloves for blood/body fluids (A), hand hygiene after PPE removal (B), and safe sharps disposal (D). Negative-pressure isolation (C) is for airborne precautions only; sterile gowns for every contact (E) are not required universally.',
 'Clinical Abbreviations in Context', 334),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'If a patient is prescribed "contact precautions," which of the following PPE items must the nurse wear when entering the room? Select all that apply.',
 '[{"id":"a","text":"A surgical mask."},{"id":"b","text":"Clean gloves."},{"id":"c","text":"An N95 respirator."},{"id":"d","text":"A clean gown."},{"id":"e","text":"Goggles or a face shield."}]'::jsonb,
 ARRAY['b','d'], true,
 'Contact precautions require a gown (D) and gloves (B) to prevent direct-contact transmission. Surgical masks (A) and goggles (E) are for droplet precautions; N95 respirators (C) are for airborne precautions.',
 'Clinical Abbreviations in Context', 335),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'In the event of a "fire" in a clinical setting, which of the following actions align with the "RACE" protocol? Select all that apply.',
 '[{"id":"a","text":"Rescuing patients in immediate danger."},{"id":"b","text":"Activating the fire alarm system."},{"id":"c","text":"Confining the fire by opening all doors and windows."},{"id":"d","text":"Extinguishing the fire if it is safe to do so."},{"id":"e","text":"Running as fast as possible to the nearest exit."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'RACE stands for Rescue (A), Alarm (B), Confine/Contain, and Extinguish (D). Doors should be *closed* to confine fire (C); never open windows. Staff should walk calmly, never run (E).',
 'Clinical Abbreviations in Context', 336),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Should a patient be prescribed a diet consisting of "clear liquids," which of the following substances would be deemed appropriate for ingestion? Select all that apply.',
 '[{"id":"a","text":"Fat-free chicken broth."},{"id":"b","text":"Apple juice without sediment."},{"id":"c","text":"Chocolate-flavored milk."},{"id":"d","text":"Gelatin desserts."},{"id":"e","text":"Vanilla-flavored yogurt."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'Clear liquids must be transparent and liquid at room temperature. Broth (A), apple juice (B), and gelatin (D) qualify. Chocolate milk (C) and yogurt (E) are opaque and not permitted.',
 'Clinical Abbreviations in Context', 337),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following vital signs are typically within the normal range for a healthy adult at rest? Select all that apply.',
 '[{"id":"a","text":"A heart rate of 72 beats per minute."},{"id":"b","text":"A respiratory rate of 8 breaths per minute."},{"id":"c","text":"A blood pressure of 118/76 mmHg."},{"id":"d","text":"An oral temperature of 37° Celsius."},{"id":"e","text":"An oxygen saturation of 88% on room air."}]'::jsonb,
 ARRAY['a','c','d'], true,
 'HR 72 bpm (A), BP 118/76 (C), and Temp 37°C (D) are all within normal adult ranges. RR of 8 (B) is too slow (normal 12–20); O2 sat of 88% (E) is below the acceptable threshold of ≥95%.',
 'Clinical Abbreviations in Context', 338),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following describe standard adult vital sign ranges? Select all that apply.',
 '[{"id":"a","text":"BP 140/90 mmHg."},{"id":"b","text":"Pulse 60-100 bpm."},{"id":"c","text":"RR 12-20 breaths per minute."},{"id":"d","text":"Temp 36.5-37.5°C."},{"id":"e","text":"O2 Sat 95-100%."}]'::jsonb,
 ARRAY['b','c','d','e'], true,
 'Normal pulse (B), respiratory rate (C), temperature (D), and oxygen saturation (E) ranges are correct. A BP of 140/90 (A) meets the threshold for Stage 2 hypertension, not normal.',
 'Clinical Abbreviations in Context', 339),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following are normal adult vital signs? Select all that apply.',
 '[{"id":"a","text":"RR 16 breaths/minute."},{"id":"b","text":"HR 110 bpm."},{"id":"c","text":"BP 110/70 mmHg."},{"id":"d","text":"Temp 98.6°F."},{"id":"e","text":"O2 Sat 92%."}]'::jsonb,
 ARRAY['a','c','d'], true,
 'RR of 16 (A), BP 110/70 (C), and Temp 98.6°F/37°C (D) are normal. HR of 110 (B) is tachycardia; O2 sat of 92% (E) is below the normal range of ≥95%.',
 'Clinical Abbreviations in Context', 340),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following actions are essential components of hand hygiene when utilizing soap and water? Select all that apply.',
 '[{"id":"a","text":"Rinsing the hands with the fingertips pointing upward."},{"id":"b","text":"Utilizing friction for a duration of no less than 20 seconds."},{"id":"c","text":"Drying the hands with a single-use towel."},{"id":"d","text":"Turning off the faucet with the bare, clean hand."},{"id":"e","text":"Ensuring the water temperature is boiling to kill bacteria."}]'::jsonb,
 ARRAY['b','c'], true,
 'Scrubbing with friction for at least 20 seconds (B) and drying with a single-use disposable towel (C) are correct technique. Fingertips should point *down* when rinsing (A). The faucet should be turned off using the towel (D) to prevent recontamination. Water should be warm, not boiling (E).',
 'Clinical Abbreviations in Context', 341),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following describe proper handwashing technique? Select all that apply.',
 '[{"id":"a","text":"Wash for at least 20 seconds."},{"id":"b","text":"Use warm water."},{"id":"c","text":"Use plenty of soap."},{"id":"d","text":"Dry from fingertips down to wrists."},{"id":"e","text":"Clean under the fingernails."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Time (A), warm water (B), soap (C), and cleaning under nails (E) are all proper technique. You should dry from the *cleanest* area (fingertips) *up* toward the wrists — drying downward (D) is incorrect.',
 'Clinical Abbreviations in Context', 342),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following are safe practices for oxygen therapy in the home? Select all that apply.',
 '[{"id":"a","text":"Smoking a cigarette at least 10 feet away from the oxygen source."},{"id":"b","text":"Utilizing cotton bedding instead of synthetic materials."},{"id":"c","text":"Ensuring the oxygen tanks are stored in a vertical, secured position."},{"id":"d","text":"Utilizing petroleum-based ointments on the nose to prevent dryness."},{"id":"e","text":"Keeping the oxygen equipment away from open flames."}]'::jsonb,
 ARRAY['b','c','e'], true,
 'Cotton bedding (B), vertical secured tank storage (C), and keeping away from flames (E) are safe. Smoking is never permitted near oxygen — not even 10 feet away (A). Petroleum-based products (D) are flammable; water-based lubricants should be used instead.',
 'Clinical Abbreviations in Context', 343),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following describe "aseptic" technique? Select all that apply.',
 '[{"id":"a","text":"The utilization of sterile gloves for a surgical procedure."},{"id":"b","text":"The cleaning of a bedside table with a disinfectant."},{"id":"c","text":"The practice of handwashing before and after patient contact."},{"id":"d","text":"The intentional introduction of bacteria into a wound."},{"id":"e","text":"The use of an autoclave to sterilize surgical instruments."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Sterile gloves (A), surface disinfection (B), handwashing (C), and autoclaving (E) are all aseptic technique components. Intentionally introducing bacteria (D) is the opposite of asepsis.',
 'Clinical Abbreviations in Context', 344),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Regarding the cessation of bacterial growth through chemical means, which of the following terms describes the complete eradication of all viable life forms? Select all that apply.',
 '[{"id":"a","text":"Disinfection."},{"id":"b","text":"Sanitization."},{"id":"c","text":"Sterilization."},{"id":"d","text":"Antisepsis."},{"id":"e","text":"Autoclaving."}]'::jsonb,
 ARRAY['c','e'], true,
 'Sterilization (C) is the complete destruction of all microbial life, including spores. Autoclaving (E) is a method of achieving sterilization through pressurized steam. Disinfection (A), sanitization (B), and antisepsis (D) reduce microbial counts but do not eliminate all life forms.',
 'Clinical Abbreviations in Context', 345),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following factors can lead to a false high blood pressure reading? Select all that apply.',
 '[{"id":"a","text":"Utilizing a cuff that is too small for the patient''s arm."},{"id":"b","text":"Positioning the arm above the level of the heart."},{"id":"c","text":"The patient crossing their legs during the measurement."},{"id":"d","text":"Deflating the cuff too slowly."},{"id":"e","text":"The patient having just consumed a caffeinated beverage."}]'::jsonb,
 ARRAY['a','c','d','e'], true,
 'A too-small cuff (A), crossed legs (C), slow cuff deflation (D), and recent caffeine intake (E) all artificially raise the reading. Positioning the arm *above* the heart (B) actually produces a false *low* reading.',
 'Clinical Abbreviations in Context', 346),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following describe "systolic" blood pressure? Select all that apply.',
 '[{"id":"a","text":"The pressure in the arteries when the heart is at rest."},{"id":"b","text":"The pressure in the arteries during ventricular contraction."},{"id":"c","text":"The top number in a blood pressure reading."},{"id":"d","text":"The bottom number in a blood pressure reading."},{"id":"e","text":"The point where the first Korotkoff sound is heard."}]'::jsonb,
 ARRAY['b','c','e'], true,
 'Systolic pressure is produced by ventricular contraction (B), appears as the top number (C), and corresponds to the first Korotkoff sound heard during auscultation (E). The resting/diastolic pressure is the bottom number (A/D).',
 'Clinical Abbreviations in Context', 347),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following are characteristics of venous blood? Select all that apply.',
 '[{"id":"a","text":"It is typically a brighter red color due to high oxygen."},{"id":"b","text":"It is typically a darker red color due to low oxygen."},{"id":"c","text":"It is traveling away from the heart."},{"id":"d","text":"It is traveling toward the heart."},{"id":"e","text":"It is under lower pressure than arterial blood."}]'::jsonb,
 ARRAY['b','d','e'], true,
 'Veins carry deoxygenated blood that is darker red (B), travel toward the heart (D), and operate under low pressure (E). Bright red, high-oxygen blood traveling away from the heart (A, C) describes arterial blood.',
 'Clinical Abbreviations in Context', 348),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'Which of the following are characteristics of arterial blood? Select all that apply.',
 '[{"id":"a","text":"It is usually bright red due to high oxygen."},{"id":"b","text":"It is under high pressure."},{"id":"c","text":"It travels away from the heart."},{"id":"d","text":"It travels toward the heart."},{"id":"e","text":"It is usually dark red due to low oxygen."}]'::jsonb,
 ARRAY['a','b','c'], true,
 'Arteries carry oxygenated blood that is bright red (A), under high pressure from cardiac output (B), and flow *away* from the heart (C — remember: Artery = Away). Dark, low-oxygen blood toward the heart (D, E) describes venous blood.',
 'Clinical Abbreviations in Context', 349),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000400',
 'If a patient is diagnosed with "anemia," they have a deficiency in which of the following? Select all that apply.',
 '[{"id":"a","text":"Leukocytes."},{"id":"b","text":"Erythrocytes."},{"id":"c","text":"Hemoglobin."},{"id":"d","text":"Thrombocytes."},{"id":"e","text":"Plasma proteins."}]'::jsonb,
 ARRAY['b','c'], true,
 'Anemia is defined as a deficiency of red blood cells (erythrocytes, B) or the hemoglobin they carry (C), resulting in reduced oxygen-carrying capacity. Leukocytes (A) are white cells; thrombocytes (D) are platelets; plasma proteins (E) are separate.',
 'Clinical Abbreviations in Context', 350),

-- =============================================
-- Q351–Q370: Clinical Scenario Reading I (SATA)
-- =============================================

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Should a nurse encounter a patient experiencing "orthostatic hypotension," which of the following physiological events would the nurse expect to observe concurrently with the patient''s transition from a recumbent to a vertical position? Select all that apply.',
 '[{"id":"a","text":"A significant elevation in systolic blood pressure."},{"id":"b","text":"A precipitous decline in systolic blood pressure."},{"id":"c","text":"A sensation characterized by lightheadedness or vertigo."},{"id":"d","text":"A transient loss of consciousness known as syncope."},{"id":"e","text":"A compensatory increase in the frequency of cardiac contractions."}]'::jsonb,
 ARRAY['b','c','d','e'], true,
 'Orthostatic (postural) hypotension involves a drop in BP of ≥20 systolic (B) upon standing, leading to dizziness/vertigo (C), possible fainting/syncope (D), and a compensatory increase in heart rate (E) as the body attempts to maintain perfusion.',
 'Clinical Scenario Reading I', 351),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following conditions would likely result in the clinical manifestation of "tachycardia"? Select all that apply.',
 '[{"id":"a","text":"A state of intense physical exertion."},{"id":"b","text":"A significant reduction in systemic blood volume."},{"id":"c","text":"A state of deep, restorative sleep."},{"id":"d","text":"An elevated body temperature (fever)."},{"id":"e","text":"The experience of acute psychological stress or anxiety."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Tachycardia (HR > 100) is triggered by exercise (A), hemorrhage/blood loss (B), fever (D — for every 1°C rise, HR rises ~10 bpm), and stress/anxiety (E). Sleep (C) characteristically produces bradycardia.',
 'Clinical Scenario Reading I', 352),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'If a patient is described as "dyspneic," which of the following clinical findings would the nurse expect to observe? Select all that apply.',
 '[{"id":"a","text":"An increased frequency of respiratory cycles."},{"id":"b","text":"The utilization of accessory muscles to facilitate breathing."},{"id":"c","text":"A verbal report of shortness of breath."},{"id":"d","text":"A pulse oximetry reading of 100% on room air."},{"id":"e","text":"Flaring of the nasal alae."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Dyspnea (difficulty breathing) presents with tachypnea (A), accessory muscle use (B), patient complaint of SOB (C), and nasal flaring (E). A perfect 100% O2 sat (D) would not be expected in a dyspneic patient.',
 'Clinical Scenario Reading I', 353),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following findings would be considered "abnormal" during an assessment of the respiratory system? Select all that apply.',
 '[{"id":"a","text":"Vesicular breath sounds over the peripheral lung fields."},{"id":"b","text":"The presence of audible wheezing upon expiration."},{"id":"c","text":"A respiratory rate of 28 breaths per minute."},{"id":"d","text":"Cyanosis of the circumoral region."},{"id":"e","text":"Symmetrical chest expansion during inspiration."}]'::jsonb,
 ARRAY['b','c','d'], true,
 'Expiratory wheezing (B), a RR of 28 (C — normal is 12–20), and circumoral cyanosis (D — blue coloring around the mouth) are abnormal findings. Vesicular sounds in peripheral fields (A) and symmetrical expansion (E) are normal.',
 'Clinical Scenario Reading I', 354),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following are signs of "respiratory distress"? Select all that apply.',
 '[{"id":"a","text":"Use of the sternocleidomastoid muscles during inhalation."},{"id":"b","text":"Inability to speak in full sentences."},{"id":"c","text":"An oxygen saturation of 94%."},{"id":"d","text":"Paradoxical chest movement."},{"id":"e","text":"Cyanosis of the nail beds."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Accessory neck muscle use (A), inability to form full sentences (B), paradoxical/seesaw chest movement (D), and peripheral cyanosis (E) all indicate respiratory distress. An O2 sat of 94% (C) is slightly below ideal but not necessarily indicative of acute distress on its own.',
 'Clinical Scenario Reading I', 355),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following would be considered "abnormal" findings for an adult heart rate? Select all that apply.',
 '[{"id":"a","text":"48 beats per minute."},{"id":"b","text":"72 beats per minute."},{"id":"c","text":"104 beats per minute."},{"id":"d","text":"140 beats per minute."},{"id":"e","text":"88 beats per minute."}]'::jsonb,
 ARRAY['a','c','d'], true,
 'Normal adult HR is 60–100 bpm. A rate of 48 (A) is bradycardia; 104 (C) and 140 (D) are tachycardia. Rates of 72 (B) and 88 (E) are within normal range.',
 'Clinical Scenario Reading I', 356),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'A patient experiencing "hypoglycemia" would likely exhibit which of the following signs or symptoms? Select all that apply.',
 '[{"id":"a","text":"Profuse diaphoresis."},{"id":"b","text":"A state of mental confusion or irritability."},{"id":"c","text":"Tremors or shakiness of the extremities."},{"id":"d","text":"Extreme thirst and excessive urination."},{"id":"e","text":"A sensation of intense hunger."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Low blood sugar triggers the adrenergic response: sweating (A), confusion/irritability (B), tremors (C), and hunger (E) as the body signals the need for glucose. Polydipsia and polyuria (D) are hallmark signs of *hyperglycemia*.',
 'Clinical Scenario Reading I', 357),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'A patient who is "dehydrated" would likely show which of the following clinical signs? Select all that apply.',
 '[{"id":"a","text":"A decrease in urinary output."},{"id":"b","text":"Dry mucous membranes."},{"id":"c","text":"A decrease in skin turgor (tenting)."},{"id":"d","text":"A rapid, thready pulse."},{"id":"e","text":"An increase in blood pressure."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'Dehydration results in decreased urine output (A), dry membranes (B), poor skin turgor (C), and a rapid, weak pulse (D) as cardiac output falls. Blood pressure typically *drops* (hypotension) with dehydration (E).',
 'Clinical Scenario Reading I', 358),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following findings would characterize a patient experiencing "hyperthermia"? Select all that apply.',
 '[{"id":"a","text":"A rectal temperature measurement of 103°F."},{"id":"b","text":"The presence of a flushed or erythematous facial appearance."},{"id":"c","text":"A heart rate that is significantly lower than 60 beats per minute."},{"id":"d","text":"An increased frequency of cardiac contractions."},{"id":"e","text":"A core temperature exceeding 38.5°C."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Hyperthermia is characterized by high temperature (A — 103°F = 39.4°C, and E — above 38.5°C), flushed/red skin (B) from cutaneous vasodilation, and compensatory tachycardia (D). Bradycardia (C) is not an expected finding.',
 'Clinical Scenario Reading I', 359),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'When a nurse is evaluating a patient''s "integumentary turgor" to assess for fluid volume deficit, which of the following results would indicate a state of dehydration? Select all that apply.',
 '[{"id":"a","text":"The skin immediately returns to its original contour."},{"id":"b","text":"The skin remains in a tented position for several seconds."},{"id":"c","text":"The mucous membranes appear moist and pink."},{"id":"d","text":"The fontanels of an infant appear depressed or sunken."},{"id":"e","text":"The patient''s urinary output is dark and concentrated."}]'::jsonb,
 ARRAY['b','d','e'], true,
 'Skin tenting that persists (B), sunken fontanels in infants (D), and dark concentrated urine (E) all indicate dehydration/fluid volume deficit. Immediate skin recoil (A) and moist pink membranes (C) are normal, well-hydrated findings.',
 'Clinical Scenario Reading I', 360),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following clinical findings would characterize a patient diagnosed with "dehydration" in an elderly patient? Select all that apply.',
 '[{"id":"a","text":"Confusion or altered mental status."},{"id":"b","text":"Furrowed tongue."},{"id":"c","text":"Hypertension."},{"id":"d","text":"Hypotension."},{"id":"e","text":"Dark, amber-colored urine."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Dehydration in the elderly often presents as confusion (A), a furrowed/dry tongue (B), hypotension (D) due to low circulating volume, and dark concentrated urine (E). Hypertension (C) is not a typical finding; BP usually drops.',
 'Clinical Scenario Reading I', 361),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following are symptoms of "hypoxia"? Select all that apply.',
 '[{"id":"a","text":"Cyanosis."},{"id":"b","text":"Confusion."},{"id":"c","text":"Increased heart rate."},{"id":"d","text":"Deep, slow breathing."},{"id":"e","text":"Restlessness."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Hypoxia (insufficient tissue oxygen) produces cyanosis (A), cognitive impairment/confusion (B), compensatory tachycardia (C), and restlessness/agitation (E). Breathing typically becomes *rapid and shallow*, not deep and slow (D).',
 'Clinical Scenario Reading I', 362),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'If a patient is in "shock," which of the following vital sign trends would the nurse expect to see? Select all that apply.',
 '[{"id":"a","text":"A decrease in blood pressure (hypotension)."},{"id":"b","text":"An increase in heart rate (tachycardia)."},{"id":"c","text":"An increase in blood pressure (hypertension)."},{"id":"d","text":"An increase in respiratory rate (tachypnea)."},{"id":"e","text":"A decrease in heart rate (bradycardia)."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'Shock is characterized by hypotension (A) as cardiac output falls, compensatory tachycardia (B) as the heart attempts to maintain perfusion, and tachypnea (D) as the body compensates for lactic acidosis. Hypertension (C) and bradycardia (E) are not typical shock findings.',
 'Clinical Scenario Reading I', 363),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following are potential complications of "hypertension" if left untreated for a prolonged duration? Select all that apply.',
 '[{"id":"a","text":"Damage to the retinal vasculature (vision loss)."},{"id":"b","text":"Hypertrophy of the left ventricle of the heart."},{"id":"c","text":"Increased risk of a cerebrovascular accident (stroke)."},{"id":"d","text":"Significant impairment of renal function."},{"id":"e","text":"An increase in joint flexibility."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'Chronic hypertension damages end organs: retinal vessels (A — hypertensive retinopathy), heart muscle (B — left ventricular hypertrophy), cerebral vessels (C — stroke risk), and nephrons (D — hypertensive nephropathy). Joint flexibility (E) is unrelated to blood pressure.',
 'Clinical Scenario Reading I', 364),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'A patient who is "immobile" is at an increased risk for which of the following complications? Select all that apply.',
 '[{"id":"a","text":"The development of pressure ulcers."},{"id":"b","text":"The formation of blood clots (DVT)."},{"id":"c","text":"Muscle atrophy."},{"id":"d","text":"Improved joint flexibility."},{"id":"e","text":"Pneumonia."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Immobility promotes pressure ulcers (A) from sustained compression, DVT (B) from venous stasis, muscle wasting (C) from disuse, and hypostatic pneumonia (E) from shallow breathing. Joint flexibility (D) *decreases* with immobility — contractures develop.',
 'Clinical Scenario Reading I', 365),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following are common adverse effects of opioid analgesics? Select all that apply.',
 '[{"id":"a","text":"Respiratory depression."},{"id":"b","text":"Constipation."},{"id":"c","text":"Diarrhea."},{"id":"d","text":"Sedation or drowsiness."},{"id":"e","text":"Urinary retention."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Opioids depress the CNS and slow body systems: respiratory depression (A), constipation from slowed GI motility (B), sedation (D), and urinary retention from decreased bladder tone (E). Diarrhea (C) is not an opioid effect — the opposite is true.',
 'Clinical Scenario Reading I', 366),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following describe "passive" immunity? Select all that apply.',
 '[{"id":"a","text":"It is acquired through the administration of a vaccine."},{"id":"b","text":"It is acquired through the transfer of antibodies from mother to fetus."},{"id":"c","text":"It is immediate but short-lived."},{"id":"d","text":"It requires the body to produce its own antibodies."},{"id":"e","text":"It is acquired through an injection of immune globulin."}]'::jsonb,
 ARRAY['b','c','e'], true,
 'Passive immunity involves receiving pre-formed antibodies: transplacental transfer (B), or injection of immunoglobulin (E). It is fast-acting but temporary (C) because no memory cells are created. Vaccines (A) and self-produced antibodies (D) are *active* immunity.',
 'Clinical Scenario Reading I', 367),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following describe "active" immunity? Select all that apply.',
 '[{"id":"a","text":"It is produced by the person''s own immune system."},{"id":"b","text":"It is permanent or long-lasting."},{"id":"c","text":"It is acquired through the administration of a vaccine."},{"id":"d","text":"It is acquired after having the disease."},{"id":"e","text":"It is immediate but very short-lived."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'Active immunity is generated by the individual''s own immune system (A), creates immunological memory making it long-lasting (B), and is acquired via vaccination (C) or natural infection (D). Short-lived immediate immunity (E) describes passive immunity.',
 'Clinical Scenario Reading I', 368),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'Which of the following are considered "primary" lymphoid organs? Select all that apply.',
 '[{"id":"a","text":"The spleen."},{"id":"b","text":"The thymus."},{"id":"c","text":"The lymph nodes."},{"id":"d","text":"The bone marrow."},{"id":"e","text":"The tonsils."}]'::jsonb,
 ARRAY['b','d'], true,
 'Primary lymphoid organs are where immune cells are *produced and mature*: bone marrow (D) for B cells and the thymus (B) for T cells. Spleen (A), lymph nodes (C), and tonsils (E) are secondary lymphoid organs where immune responses occur.',
 'Clinical Scenario Reading I', 369),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000401',
 'In a patient diagnosed with "jaundice," which of the following anatomical sites would be most likely to exhibit a yellow discoloration? Select all that apply.',
 '[{"id":"a","text":"The sclera of the eyes."},{"id":"b","text":"The palms of the hands."},{"id":"c","text":"The mucous membranes of the mouth."},{"id":"d","text":"The follicles of the hair."},{"id":"e","text":"The surface of the integument."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Jaundice (icterus) from bilirubin accumulation discolors the sclera (A), skin including palms (B, E), and mucous membranes (C). Hair follicles (D) contain keratin and do not absorb bilirubin in a way that produces visible discoloration.',
 'Clinical Scenario Reading I', 370),

-- =============================================
-- Q371–Q390: Clinical Scenario Reading II (SATA)
-- =============================================

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'If a patient is "diaphoretic," the nurse should check for which of the following? Select all that apply.',
 '[{"id":"a","text":"Fever."},{"id":"b","text":"Low blood sugar (hypoglycemia)."},{"id":"c","text":"Pain."},{"id":"d","text":"Dehydration."},{"id":"e","text":"High blood pressure."}]'::jsonb,
 ARRAY['a','b','c'], true,
 'Diaphoresis (excessive sweating) is associated with fever (A), hypoglycemia (B — adrenergic response), and pain (C — sympathetic activation). Dehydration (D) typically *decreases* perspiration. Hypertension (E) does not typically cause diaphoresis unless in hypertensive crisis.',
 'Clinical Scenario Reading II', 371),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'In the event that a patient''s arterial oxygen saturation is quantified via infrared light transmission, which of the following factors could result in an inaccurate numerical value? Select all that apply.',
 '[{"id":"a","text":"The presence of dark-colored nail polish."},{"id":"b","text":"Significant movement of the extremity being measured."},{"id":"c","text":"A state of localized peripheral vasoconstriction."},{"id":"d","text":"The patient''s underlying skin pigmentation."},{"id":"e","text":"The presence of carbon monoxide in the hemoglobin."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Pulse oximetry accuracy is impaired by dark nail polish (A), motion artifact (B), poor perfusion/vasoconstriction (C), and carboxyhemoglobin (CO poisoning, E — the device reads it as oxygenated). Modern sensors are generally not affected by skin pigmentation alone (D).',
 'Clinical Scenario Reading II', 372),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following descriptors are applicable to the anatomical position of the kidneys? Select all that apply.',
 '[{"id":"a","text":"They are located in the retroperitoneal space."},{"id":"b","text":"They are situated superior to the adrenal glands."},{"id":"c","text":"They are positioned posterior to the abdominal cavity."},{"id":"d","text":"They are lateral to the vertebral column."},{"id":"e","text":"They are inferior to the pelvic floor."}]'::jsonb,
 ARRAY['a','c','d'], true,
 'The kidneys lie in the retroperitoneal space (A/C — behind the peritoneum and posterior to the abdominal organs) and lateral to the vertebral column (D). The adrenal glands sit *on top of* the kidneys, making the kidneys inferior to them (B is wrong). The kidneys are far superior to the pelvic floor (E is wrong).',
 'Clinical Scenario Reading II', 373),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following clinical findings would characterize a patient experiencing "hyperthermia"? Select all that apply.',
 '[{"id":"a","text":"Rectal temperature of 103°F."},{"id":"b","text":"Flushed facial appearance."},{"id":"c","text":"Heart rate significantly lower than 60 bpm."},{"id":"d","text":"Increased frequency of cardiac contractions."},{"id":"e","text":"Core temperature exceeding 38.5°C."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Hyperthermia presents with elevated core temperature (A, E), peripheral vasodilation causing flushed skin (B), and compensatory tachycardia (D). Bradycardia (C) is the opposite and not expected with fever.',
 'Clinical Scenario Reading II', 374),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following are signs of localized infection at a wound site? Select all that apply.',
 '[{"id":"a","text":"Purulent drainage (pus)."},{"id":"b","text":"Localized edema (swelling)."},{"id":"c","text":"A systemic fever of 103°F."},{"id":"d","text":"Warmth to the touch at the site."},{"id":"e","text":"Increased pain or tenderness."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Local wound infection signs are confined to the wound area: purulent exudate (A), localized swelling (B), site warmth (D), and local tenderness/pain (E). A high systemic fever (C) indicates the infection has become *systemic*, not merely localized.',
 'Clinical Scenario Reading II', 375),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following are cardinal signs of infection in a surgical wound? Select all that apply.',
 '[{"id":"a","text":"Erythema (redness)."},{"id":"b","text":"Edema (swelling)."},{"id":"c","text":"Purulent exudate (pus)."},{"id":"d","text":"Approximation of the wound margins."},{"id":"e","text":"Hyperthermia (heat) at the site."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Local wound infection is marked by redness (A), swelling (B), pus (C), and heat (E) — representing the cardinal signs of inflammation plus infection. Wound approximation/edge closure (D) is a sign of normal *healing*, not infection.',
 'Clinical Scenario Reading II', 376),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following are characteristics of a "Stage 2" pressure ulcer? Select all that apply.',
 '[{"id":"a","text":"Intact skin with non-blanchable redness."},{"id":"b","text":"Partial-thickness loss of the dermis."},{"id":"c","text":"A shallow, open ulcer with a red-pink wound bed."},{"id":"d","text":"Visible subcutaneous fat and muscle tissue."},{"id":"e","text":"The presence of an intact or ruptured serum-filled blister."}]'::jsonb,
 ARRAY['b','c','e'], true,
 'Stage 2 pressure ulcers have partial-thickness skin loss (B), a shallow wound bed (C), or a serum blister (E). Non-blanchable intact skin (A) is Stage 1; visible fat/muscle (D) is Stage 3/4.',
 'Clinical Scenario Reading II', 377),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following findings are typical of "Stage 1" pressure ulcers? Select all that apply.',
 '[{"id":"a","text":"Intact skin."},{"id":"b","text":"Non-blanchable redness."},{"id":"c","text":"A deep, open crater."},{"id":"d","text":"Localized pain or warmth."},{"id":"e","text":"Visible bone or muscle."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'Stage 1 is the earliest stage: skin is still intact (A) but shows non-blanchable erythema (B) and may be warm or tender (D). Deep craters (C) indicate Stage 3; visible bone/muscle (E) indicate Stage 4.',
 'Clinical Scenario Reading II', 378),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following describe "Stage 4" pressure ulcers? Select all that apply.',
 '[{"id":"a","text":"Full-thickness skin loss."},{"id":"b","text":"Visible bone, tendon, or muscle."},{"id":"c","text":"Often includes undermining or tunneling."},{"id":"d","text":"Red, intact skin."},{"id":"e","text":"A shallow, pink wound bed."}]'::jsonb,
 ARRAY['a','b','c'], true,
 'Stage 4 is the most severe: full-thickness tissue loss (A) exposing bone/tendon/muscle (B), often with undermining or tunneling (C). Intact red skin (D) is Stage 1; a shallow pink wound bed (E) is Stage 2.',
 'Clinical Scenario Reading II', 379),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Regarding "proper" body mechanics for a clinician tasked with lifting a heavy object, which of the following techniques should be avoided to prevent musculoskeletal injury? Select all that apply.',
 '[{"id":"a","text":"Maintaining a wide base of support with the feet."},{"id":"b","text":"Bending at the waist while keeping the knees locked in extension."},{"id":"c","text":"Utilizing the large muscles of the lower extremities for power."},{"id":"d","text":"Twisting the torso while carrying the load."},{"id":"e","text":"Holding the object as far away from the body as possible."}]'::jsonb,
 ARRAY['b','d','e'], true,
 'The question asks what to *avoid*. Bending from the waist with straight knees (B) strains the lower back; twisting while loaded (D) is a leading cause of spinal injury; and holding objects away from the body (E) increases the lever arm and mechanical strain. Wide stance (A) and using leg muscles (C) are *correct* techniques.',
 'Clinical Scenario Reading II', 380),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'A patient in the "Sims" position would be oriented in which of the following ways? Select all that apply.',
 '[{"id":"a","text":"Lying on their side (usually the left)."},{"id":"b","text":"Lying flat on their back."},{"id":"c","text":"Having the upper knee flexed toward the chest."},{"id":"d","text":"Having the lower arm positioned behind them."},{"id":"e","text":"Sitting upright at a 45-degree angle."}]'::jsonb,
 ARRAY['a','c','d'], true,
 'Sims position is a semi-prone, side-lying position (usually left side, A) with the upper knee drawn toward the chest (C) and the lower arm positioned posteriorly behind the body (D). Back-lying (B) is supine; 45-degree upright (E) is semi-Fowler''s.',
 'Clinical Scenario Reading II', 381),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following describe "Full-Fowler''s" position? Select all that apply.',
 '[{"id":"a","text":"The patient is sitting upright at a 90-degree angle."},{"id":"b","text":"The patient''s knees may be slightly elevated."},{"id":"c","text":"The patient is lying flat on their back."},{"id":"d","text":"The position is often utilized to facilitate breathing."},{"id":"e","text":"The patient is lying on their abdomen."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'Full-Fowler''s is a fully upright sitting position at 90° (A), often with a slight knee elevation for comfort (B), used to maximize lung expansion and ease breathing (D). Flat back-lying (C) is supine; abdomen-lying (E) is prone.',
 'Clinical Scenario Reading II', 382),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'A patient in the "prone" position is oriented in which of the following ways? Select all that apply.',
 '[{"id":"a","text":"Lying on their anterior surface."},{"id":"b","text":"Lying flat on their back."},{"id":"c","text":"Lying with their face turned to the side for comfort."},{"id":"d","text":"Lying on their abdomen."},{"id":"e","text":"Having the head elevated at 30 degrees."}]'::jsonb,
 ARRAY['a','c','d'], true,
 'Prone is belly-down/anterior surface down (A, D) with the head turned to maintain a patent airway (C). Lying on the back (B) is supine. Head elevation (E) is not characteristic of the standard prone position.',
 'Clinical Scenario Reading II', 383),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Regarding "passive" range of motion exercises, which of the following statements are correct? Select all that apply.',
 '[{"id":"a","text":"The exercises are performed entirely by the patient without assistance."},{"id":"b","text":"The exercises are performed by the nurse or a machine for the patient."},{"id":"c","text":"The purpose is to maintain joint mobility."},{"id":"d","text":"The nurse should move the joint beyond the point of resistance or pain."},{"id":"e","text":"The nurse should support the limb above and below the joint."}]'::jsonb,
 ARRAY['b','c','e'], true,
 'Passive ROM is performed *by the caregiver or device* (B), not the patient, to maintain joint flexibility and prevent contractures (C). The limb is supported above and below the joint (E) to prevent injury. The joint should never be forced past resistance or pain (D would cause harm). Self-performed exercises (A) describe active ROM.',
 'Clinical Scenario Reading II', 384),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following are common "subjective" symptoms? Select all that apply.',
 '[{"id":"a","text":"Nausea."},{"id":"b","text":"Fatigue."},{"id":"c","text":"A rash."},{"id":"d","text":"Anxiety."},{"id":"e","text":"Pain."}]'::jsonb,
 ARRAY['a','b','d','e'], true,
 'Subjective data is what the *patient reports feeling* and cannot be directly measured: nausea (A), fatigue (B), anxiety (D), and pain (E). A rash (C) can be directly *observed and measured* by the clinician — it is objective data.',
 'Clinical Scenario Reading II', 385),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following describe "subjective" data? Select all that apply.',
 '[{"id":"a","text":"My head hurts."},{"id":"b","text":"A blood pressure of 120/80."},{"id":"c","text":"I feel dizzy."},{"id":"d","text":"A weight of 150 lbs."},{"id":"e","text":"I haven''t slept well."}]'::jsonb,
 ARRAY['a','c','e'], true,
 'Subjective data is reported by the patient and cannot be independently verified: headache complaint (A), dizziness feeling (C), and sleep difficulty (E). Blood pressure (B) and weight (D) are measured, making them objective data.',
 'Clinical Scenario Reading II', 386),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following describe "acute" pain? Select all that apply.',
 '[{"id":"a","text":"It is of sudden onset."},{"id":"b","text":"It lasts for more than 6 months."},{"id":"c","text":"It usually serves as a warning of tissue damage."},{"id":"d","text":"It disappears once the underlying cause is healed."},{"id":"e","text":"It is often accompanied by increased heart rate and blood pressure."}]'::jsonb,
 ARRAY['a','c','d','e'], true,
 'Acute pain is sudden in onset (A), serves a protective/warning function (C), resolves with healing (D), and activates the sympathetic stress response causing elevated HR and BP (E). Pain lasting more than 3–6 months (B) is defined as *chronic* pain.',
 'Clinical Scenario Reading II', 387),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following are "therapeutic" communication techniques? Select all that apply.',
 '[{"id":"a","text":"Giving advice."},{"id":"b","text":"Active listening."},{"id":"c","text":"Asking why questions."},{"id":"d","text":"Using silence."},{"id":"e","text":"Reflecting the patient''s feelings."}]'::jsonb,
 ARRAY['b','d','e'], true,
 'Active listening (B), therapeutic silence (D), and reflecting/paraphrasing feelings (E) are therapeutic techniques that encourage expression. Giving direct advice (A) removes patient autonomy; asking "why" questions (C) can feel accusatory and is non-therapeutic.',
 'Clinical Scenario Reading II', 388),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'If a patient has "dysphagia," they should be given which of the following? Select all that apply.',
 '[{"id":"a","text":"Thickened liquids."},{"id":"b","text":"Large pieces of steak."},{"id":"c","text":"A straw for all drinks."},{"id":"d","text":"Assistance with meals."},{"id":"e","text":"A sitting position while eating."}]'::jsonb,
 ARRAY['a','d','e'], true,
 'For dysphagia (swallowing difficulty): thickened liquids (A) slow flow to allow safe swallowing; meal assistance (D) ensures safety; and upright positioning (E) uses gravity to aid swallowing. Steak (B) is a high choking risk. Straws (C) increase the speed of liquid flow, raising aspiration risk.',
 'Clinical Scenario Reading II', 389),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000402',
 'Which of the following describe proper handwashing? Select all that apply.',
 '[{"id":"a","text":"Wash for at least 20 seconds."},{"id":"b","text":"Use warm water."},{"id":"c","text":"Use plenty of soap."},{"id":"d","text":"Dry from fingertips down to wrists."},{"id":"e","text":"Clean under the fingernails."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'Effective handwashing requires adequate time (A — minimum 20 seconds), warm water (B), sufficient soap (C), and attention to nails (E — a common harboring site for pathogens). Drying should proceed from fingertips *upward* toward the wrists (D is incorrect direction).',
 'Clinical Scenario Reading II', 390),

-- =============================================
-- Q391–Q400: Professional Nursing Communication (SATA)
-- =============================================

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'Which of the following are "cardinal" signs of inflammation? Select all that apply.',
 '[{"id":"a","text":"Redness."},{"id":"b","text":"Swelling."},{"id":"c","text":"Heat."},{"id":"d","text":"Pain."},{"id":"e","text":"Numbness."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'The four cardinal signs of inflammation (from Latin: *rubor*, *tumor*, *calor*, *dolor*) are redness (A), swelling (B), heat (C), and pain (D). Numbness (E) is not a classic sign; loss of function (*functio laesa*) is sometimes cited as a fifth sign.',
 'Professional Nursing Communication', 391),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'Which of the following signs are associated with "inflammation"? Select all that apply.',
 '[{"id":"a","text":"Rubor (redness)."},{"id":"b","text":"Tumor (swelling)."},{"id":"c","text":"Calor (heat)."},{"id":"d","text":"Dolor (pain)."},{"id":"e","text":"Pallor (paleness)."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'The classic Latin terms for the signs of inflammation are rubor (A), tumor (B — swelling, not cancer in this context), calor (C), and dolor (D). Pallor (E) is paleness/decreased blood flow, which is the opposite of the redness seen in inflammation.',
 'Professional Nursing Communication', 392),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'If a clinician is performing an assessment of the cranial nerves, which of the following activities would the patient be asked to perform? Select all that apply.',
 '[{"id":"a","text":"Shrugging the shoulders against resistance."},{"id":"b","text":"Protruding the tongue and moving it laterally."},{"id":"c","text":"Following a moving object with the eyes."},{"id":"d","text":"Squeezing the nurse''s hands to test grip strength."},{"id":"e","text":"Recalling what they ate for breakfast."}]'::jsonb,
 ARRAY['a','b','c'], true,
 'Cranial nerve tests include shrugging (A — CN XI spinal accessory), tongue protrusion (B — CN XII hypoglossal), and eye tracking (C — CN III, IV, VI oculomotor nerves). Grip strength (D) tests peripheral motor nerves, not cranial nerves. Memory recall (E) assesses cognition, not a specific cranial nerve.',
 'Professional Nursing Communication', 393),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'Regarding the administration of an "intramuscular" injection, which of the following anatomical sites are commonly utilized? Select all that apply.',
 '[{"id":"a","text":"The deltoid muscle."},{"id":"b","text":"The vastus lateralis."},{"id":"c","text":"The gluteus maximus (dorsogluteal)."},{"id":"d","text":"The ventrogluteal area."},{"id":"e","text":"The biceps brachii."}]'::jsonb,
 ARRAY['a','b','d'], true,
 'Preferred IM sites include the deltoid (A — small volumes in adults), vastus lateralis (B — preferred for infants and children), and ventrogluteal (D — preferred for large volumes in adults; fewer major nerves and vessels). The dorsogluteal (C) is largely avoided due to proximity to the sciatic nerve. The biceps (E) is never used for IM injection.',
 'Professional Nursing Communication', 394),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'Which of the following describe the "pH" scale in the context of human physiology? Select all that apply.',
 '[{"id":"a","text":"A pH of 7.0 is considered neutral."},{"id":"b","text":"The normal range for arterial blood is 7.35 to 7.45."},{"id":"c","text":"A pH below 7.0 is considered alkaline."},{"id":"d","text":"A pH above 7.0 is considered acidic."},{"id":"e","text":"Gastric secretions typically have a highly acidic pH."}]'::jsonb,
 ARRAY['a','b','e'], true,
 '7.0 is the neutral point (A); arterial blood pH of 7.35–7.45 is normal (B); and stomach acid has a very low pH (~1.5–3.5), making it highly acidic (E). A pH *below* 7 is acidic (C is wrong); above 7 is alkaline (D is wrong).',
 'Professional Nursing Communication', 395),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'Which of the following are parts of the inner ear? Select all that apply.',
 '[{"id":"a","text":"The pinna."},{"id":"b","text":"The cochlea."},{"id":"c","text":"The tympanic membrane."},{"id":"d","text":"The semicircular canals."},{"id":"e","text":"The ossicles."}]'::jsonb,
 ARRAY['b','d'], true,
 'The inner ear contains the cochlea (B — for hearing) and semicircular canals (D — for balance/equilibrium). The pinna (A) is the outer ear; the tympanic membrane/eardrum (C) and ossicles/bones (E) are middle ear structures.',
 'Professional Nursing Communication', 396),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'If a patient is prescribed "High-Fowler''s" position, the nurse has elevated the head of the bed to which angle? Select all that apply.',
 '[{"id":"a","text":"15 degrees."},{"id":"b","text":"30 degrees."},{"id":"c","text":"45 degrees."},{"id":"d","text":"60 degrees."},{"id":"e","text":"90 degrees."}]'::jsonb,
 ARRAY['e'], true,
 'High-Fowler''s position is defined as the head of the bed elevated to 60–90 degrees, with 90 degrees (E) being the most specific and most commonly tested angle. 30° is Low-Fowler''s; 45° is Semi-Fowler''s.',
 'Professional Nursing Communication', 397),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'If a patient is bradycardic, the nurse should do which of the following? Select all that apply.',
 '[{"id":"a","text":"Check the patient''s pulse for a full minute."},{"id":"b","text":"Assess for dizziness or fainting."},{"id":"c","text":"Notify the doctor if the heart rate is below 60."},{"id":"d","text":"Tell the patient to run a lap around the hospital."},{"id":"e","text":"Check the patient''s blood pressure."}]'::jsonb,
 ARRAY['a','b','c','e'], true,
 'For bradycardia (HR < 60): verify by counting pulse for a full minute (A), assess for hemodynamic symptoms like dizziness/syncope (B), report to the physician (C), and check BP since bradycardia can cause hypotension (E). Prescribing exercise (D) is not an appropriate clinical intervention for an arrhythmia.',
 'Professional Nursing Communication', 398),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'Which of the following are parts of the urinary tract? Select all that apply.',
 '[{"id":"a","text":"The kidneys."},{"id":"b","text":"The ureters."},{"id":"c","text":"The bladder."},{"id":"d","text":"The urethra."},{"id":"e","text":"The esophagus."}]'::jsonb,
 ARRAY['a','b','c','d'], true,
 'The urinary tract consists of the kidneys (A — produce urine), ureters (B — carry urine to bladder), bladder (C — stores urine), and urethra (D — eliminates urine). The esophagus (E) is a digestive structure connecting the pharynx to the stomach.',
 'Professional Nursing Communication', 399),

('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000403',
 'A patient with "hypercalcemia" has an excess of which mineral in their blood? Select all that apply.',
 '[{"id":"a","text":"Potassium."},{"id":"b","text":"Sodium."},{"id":"c","text":"Calcium."},{"id":"d","text":"Iron."},{"id":"e","text":"Magnesium."}]'::jsonb,
 ARRAY['c'], true,
 '"Hyper-" (excess) + "-calc-" (calcium from Latin *calx*) + "-emia" (in the blood) = elevated calcium in the blood. Only calcium (C) is correct.',
 'Professional Nursing Communication', 400);
